name: Meilisearch Indexer

on: 
  push:
    branches:
      - main
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout indexer script
      uses: actions/checkout@v3
      with:
        path: main

    - name: checkout documentation repository
      uses: actions/checkout@v3
      with:
        repository: intechstudio/grid-documentation
        path: documentation

    - name: show contents
      run: |
        ls -la
        ls -la main
        ls -la documentation
      
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: create env
      run: |
        cd main
        touch .env
        echo PATH_TO_DOCUMENTS=../documentation/docs/ >> .env
        echo MEILI_INDEX=grid-documentation >> .env
        echo MEILI_HOST=${{secrets.MEILI_HOST}} >> .env
        echo MEILI_ADMIN_KEY=${{secrets.MEILI_ADMIN_KEY}} >> .env
    
    - name: build and run indexer script
      run: | 
        cd main
        npm i
        npm build
        npm index
  
