name: Meilisearch Indexer

on: 
  push:
    branches:
      - main
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout indexer script
      uses: actions/checkout@v3
      with:
        path: main

    - name: checkout documentation repository
      uses: actions/checkout@v3
      with:
        repository: intechstudio/grid-documentation
        path: documentation

    - name: show contents
      run: |
        ls -la
    
    - name: create env
        run: |
          touch .env
          echo PATH_TO_DOCUMENTS=./ >> .env
          echo MEILI_INDEX=grid-documentation >> .env
          echo MEILI_HOST=${{secrets.MEILI_HOST}} >> .env
          echo MEILI_ADMIN_KEY=${{secrets.MEILI_ADMIN_KEY}} >> .env